### ISSUE TITLE
Can not use Notion Plugin in Flow Launcher

### ISSUE THREAD

**Issue by Crows-77** [AminSallah/Flow.Launcher.Plugin.Notion#12]
Wrong to use the Notion Plugin:

**1. Upload log file in Attachment;
2. Copy Exception message below:**
[2024-06-06.txt](https://github.com/user-attachments/files/15612397/2024-06-06.txt)

Flow Launcher version: 1.18.0
OS Version: 22631.3593
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 06/06/2024 16:36:54
Exception:
Notion Exception: 
Websites: https://github.com/AminSallah/Flow.Launcher.Plugin.Notion
Author: Amin Salah
Version: 4.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key 'fcd45790-3d04-4a14-a387-636fff6effe7' was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'fcd45790-3d04-4a14-a387-636fff6effe7' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Flow.Launcher.Plugin.Notion.Main.BuildPathChain(String pageId)
   at Flow.Launcher.Plugin.Notion.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AminSallah** [comment]
This issue should be resolved in v5. Additionally, reinstalling the plugin fixes this.
