### ISSUE TITLE
doesn't load any page

### ISSUE THREAD

**Issue by VincentLuders** [AminSallah/Flow.Launcher.Plugin.Notion#16]
message

Flow Launcher version: 1.19.0
OS Version: 22631.4037
IntPtr Length: 8
x64: True

Python Path: C:\Users\vince\AppData\Local\Microsoft\WindowsApps\python.exe
Node Path: 
Date: 08/23/2024 15:36:49
Exception:
Notion Exception: 
Websites: https://github.com/AminSallah/Flow.Launcher.Plugin.Notion
Author: Amin Salah
Version: 4.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: The given key '8ff59a0c-2eb8-4ce1-9804-b6960d12703a' was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '8ff59a0c-2eb8-4ce1-9804-b6960d12703a' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Flow.Launcher.Plugin.Notion.Main.BuildPathChain(String pageId)
   at Flow.Launcher.Plugin.Notion.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 247
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AminSallah** [comment]
This issue should be addressed in v5. To resolve it immediately, share this page [https://notion.so/8ff59a0c2eb84ce19804b6960d12703a](https://notion.so/8ff59a0c2eb84ce19804b6960d12703a) with your integration token so the plugin can access it and retrieve its title.
