### ISSUE TITLE
error when using notion plugin in flow launcher

### ISSUE THREAD

**Issue by ahmadmln** [AminSallah/Flow.Launcher.Plugin.Notion#3]
Flow Launcher version: 1.17.2
OS Version: 22631.3227
IntPtr Length: 8
x64: True

Python Path: C:\Users\Sibayak UM5302\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 02/26/2024 16:31:32
Exception:
Notion Exception: 
Websites: https://github.com/AminSallah/Flow.Launcher.Plugin.Notion
Author: Amin Salah
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.Notion.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 195
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AminSallah** [comment]
Hey @ahmadmln , This error entirely relay on what you shared with your integration token. plugin attempts to eleminate this error by set a default database to the first one returned by the Notion API.
I can infer that **you haven't shared any database with your secret code**. You can check by navigating to the plugin settings panel and ensuring that the `Default Database` is not empty. if so Please see this to share a full database with integraion

To share a database, go to the Database page and select your integration name.
- Share at least one database with the token.

        
 ![Full Database Sharing Image](https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/blob/main/assets/screenshots/FullDB.png?raw=true)

After you share the database restart flow launcher or Relod plugin data, Let me know if this fixed the issue.

**Comment by ahmadmln** [comment]
it works now, and perfectly, thanks so much
