### ISSUE TITLE
i need help, my notion plugin keeps making my flow launcher crash

### ISSUE THREAD

**Issue by zizenn** [AminSallah/Flow.Launcher.Plugin.Notion#4]
[2024-02-29.txt](https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/files/14445547/2024-02-29.txt)

Flow Launcher version: 1.16.2
OS Version: 19045.4046
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 02/29/2024 19:33:49
Exception:
Notion Exception: 
Websites: https://github.com/AminSallah/Flow.Launcher.Plugin.Notion
Author: Amin Salah
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.Notion.Main.QueryAsync(Query query, CancellationToken token)
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AminSallah** [comment]
Hey @Berkerserker, This error relay on what you shared with your internal integration token. Please refer to this for further understanding and to fix the problem #3 
Let me know if this helped.

**Comment by zizenn** [comment]
thank you it works perfectly now i have no issues :)
